import platform

print(platform.architecture())
print(platform.machine())
print(platform.node())
print(platform.platform(aliased=0, terse=0))
print(platform.processor())
print(platform.uname())
print(platform.python_build())
print(platform.python_compiler())
print(platform.python_branch())
print(platform.python_implementation())
print(platform.python_revision())
print(platform.python_version())
print(platform.release())
print(platform.system())